import { PokemonType } from './PokemonType';

export const Pokedex = {
  1: {
    name: "Bulbasaur",
    spriteId: "001",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 45,
    attack: 49,
    defense: 49,
    specialAttack: 65,
    specialDefense: 65,
    speed: 45,
    totalBaseStats: 318,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5,
    },
  },
  2: {
    name: "Ivysaur",
    spriteId: "002",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 60,
    attack: 62,
    defense: 63,
    specialAttack: 80,
    specialDefense: 80,
    speed: 60,
    totalBaseStats: 405,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5,
    },
  },
  3: {
    name: "Venusaur",
    spriteId: "003",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 80,
    attack: 82,
    defense: 83,
    specialAttack: 100,
    specialDefense: 100,
    speed: 80,
    totalBaseStats: 525,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5,
    },
  },
  4: {
    name: "Charmander",
    spriteId: "004",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 39,
    attack: 52,
    defense: 43,
    specialAttack: 60,
    specialDefense: 50,
    speed: 65,
    totalBaseStats: 309,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  5: {
    name: "Charmeleon",
    spriteId: "005",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 58,
    attack: 64,
    defense: 58,
    specialAttack: 80,
    specialDefense: 65,
    speed: 80,
    totalBaseStats: 405,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  6: {
    name: "Charizard",
    spriteId: "006",
    typeOne: "Fire",
    typeTwo: "Flying",
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.FLYING,
    hp: 78,
    attack: 84,
    defense: 78,
    specialAttack: 109,
    specialDefense: 85,
    speed: 100,
    totalBaseStats: 534,
    weaknesses: {
      Water: 2,
      Electric: 2,
      Ground: 2,
      Rock: 4,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Ground: 0,
      Bug: 0.25,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  7: {
    name: "Squirtle",
    spriteId: "007",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 44,
    attack: 48,
    defense: 65,
    specialAttack: 50,
    specialDefense: 64,
    speed: 43,
    totalBaseStats: 314,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  8: {
    name: "Wartortle",
    spriteId: "008",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 59,
    attack: 63,
    defense: 80,
    specialAttack: 65,
    specialDefense: 80,
    speed: 58,
    totalBaseStats: 405,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  9: {
    name: "Blastoise",
    spriteId: "009",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 79,
    attack: 83,
    defense: 100,
    specialAttack: 85,
    specialDefense: 105,
    speed: 78,
    totalBaseStats: 530,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  10: {
    name: "Caterpie",
    spriteId: "010",
    typeOne: "Bug",
    typeTwo: null,
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 45,
    attack: 30,
    defense: 35,
    specialAttack: 20,
    specialDefense: 20,
    speed: 45,
    totalBaseStats: 195,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Ground: 0.5,
    },
  },
  11: {
    name: "Metapod",
    spriteId: "011",
    typeOne: "Bug",
    typeTwo: null,
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 50,
    attack: 20,
    defense: 55,
    specialAttack: 25,
    specialDefense: 25,
    speed: 30,
    totalBaseStats: 205,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Ground: 0.5,
    },
  },
  12: {
    name: "Butterfree",
    spriteId: "012",
    typeOne: "Bug",
    typeTwo: "Flying",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.FLYING,
    hp: 60,
    attack: 45,
    defense: 50,
    specialAttack: 90,
    specialDefense: 80,
    speed: 70,
    totalBaseStats: 395,
    weaknesses: {
      Fire: 2,
      Electric: 2,
      Ice: 2,
      Flying: 2,
      Rock: 4,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Ground: 0,
      Bug: 0.5,
    },
  },
  13: {
    name: "Weedle",
    spriteId: "013",
    typeOne: "Bug",
    typeTwo: "Poison",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.POISON,
    hp: 40,
    attack: 35,
    defense: 30,
    specialAttack: 20,
    specialDefense: 20,
    speed: 50,
    totalBaseStats: 195,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Rock: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  14: {
    name: "Kakuna",
    spriteId: "014",
    typeOne: "Bug",
    typeTwo: "Poison",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.POISON,
    hp: 45,
    attack: 25,
    defense: 50,
    specialAttack: 25,
    specialDefense: 25,
    speed: 35,
    totalBaseStats: 205,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Rock: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  15: {
    name: "Beedrill",
    spriteId: "015",
    typeOne: "Bug",
    typeTwo: "Poison",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.POISON,
    hp: 65,
    attack: 90,
    defense: 40,
    specialAttack: 45,
    specialDefense: 80,
    speed: 75,
    totalBaseStats: 395,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Rock: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  16: {
    name: "Pidgey",
    spriteId: "016",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 40,
    attack: 45,
    defense: 40,
    specialAttack: 35,
    specialDefense: 35,
    speed: 56,
    totalBaseStats: 251,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Ghost: 0,
      Bug: 0.5,
    },
  },
  17: {
    name: "Pidgeotto",
    spriteId: "017",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 63,
    attack: 60,
    defense: 55,
    specialAttack: 50,
    specialDefense: 50,
    speed: 71,
    totalBaseStats: 349,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Ghost: 0,
      Bug: 0.5,
    },
  },
  18: {
    name: "Pidgeot",
    spriteId: "018",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 83,
    attack: 80,
    defense: 75,
    specialAttack: 70,
    specialDefense: 70,
    speed: 101,
    totalBaseStats: 479,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Ghost: 0,
      Bug: 0.5,
    },
  },
  19: {
    name: "Rattata",
    spriteId: "019",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 30,
    attack: 56,
    defense: 35,
    specialAttack: 25,
    specialDefense: 35,
    speed: 72,
    totalBaseStats: 253,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    },
  },
  20: {
    name: "Raticate",
    spriteId: "020",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 55,
    attack: 81,
    defense: 60,
    specialAttack: 50,
    specialDefense: 70,
    speed: 97,
    totalBaseStats: 413,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    },
  },
  21: {
    name: "Spearow",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 40,
    attack: 60,
    defense: 30,
    specialAttack: 31,
    specialDefense: 31,
    speed: 70,
    totalBaseStats: 262,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Ghost: 0,
      Bug: 0.5,
    },
  },
  22: {
    name: "Fearow",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 65,
    attack: 90,
    defense: 65,
    specialAttack: 61,
    specialDefense: 61,
    speed: 100,
    totalBaseStats: 442,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Ghost: 0,
      Bug: 0.5,
    },
  },
  23: {
    name: "Ekans",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 35,
    attack: 60,
    defense: 44,
    specialAttack: 40,
    specialDefense: 54,
    speed: 55,
    totalBaseStats: 288,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  24: {
    name: "Arbok",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 60,
    attack: 95,
    defense: 69,
    specialAttack: 65,
    specialDefense: 79,
    speed: 80,
    totalBaseStats: 448,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  25: {
    name: "Pikachu",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: null,
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 35,
    attack: 55,
    defense: 40,
    specialAttack: 50,
    specialDefense: 50,
    speed: 90,
    totalBaseStats: 320,
    weaknesses: {
      Ground: 2,
    },
    resistances: {
      Electric: 0.5,
      Flying: 0.5,
      Steel: 0.5,
    },
  },
  26: {
    name: "Raichu",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: null,
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 60,
    attack: 90,
    defense: 55,
    specialAttack: 90,
    specialDefense: 80,
    speed: 110,
    totalBaseStats: 485,
    weaknesses: {
      Ground: 2,
    },
    resistances: {
      Electric: 0.5,
      Flying: 0.5,
      Steel: 0.5,
    },
  },
  27: {
    name: "Sandshrew",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: null,
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 50,
    attack: 75,
    defense: 85,
    specialAttack: 20,
    specialDefense: 30,
    speed: 40,
    totalBaseStats: 300,
    weaknesses: {
      Water: 2,
      Grass: 2,
      Ice: 2,
    },
    resistances: {
      Electric: 0,
      Poison: 0.5,
      Rock: 0.5,
    },
  },
  28: {
    name: "Sandslash",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: null,
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 75,
    attack: 100,
    defense: 110,
    specialAttack: 45,
    specialDefense: 55,
    speed: 65,
    totalBaseStats: 450,
    weaknesses: {
      Water: 2,
      Grass: 2,
      Ice: 2,
    },
    resistances: {
      Electric: 0,
      Poison: 0.5,
      Rock: 0.5,
    },
  },
  29: {
    name: "Nidoran♀",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 55,
    attack: 47,
    defense: 52,
    specialAttack: 40,
    specialDefense: 40,
    speed: 41,
    totalBaseStats: 275,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  30: {
    name: "Nidorina",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 70,
    attack: 62,
    defense: 67,
    specialAttack: 55,
    specialDefense: 55,
    speed: 56,
    totalBaseStats: 365,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  31: {
    name: "Nidoqueen",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: "Ground",
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.GROUND,
    hp: 90,
    attack: 92,
    defense: 87,
    specialAttack: 75,
    specialDefense: 85,
    speed: 76,
    totalBaseStats: 505,
    weaknesses: {
      Water: 2,
      Ice: 2,
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Electric: 0,
      Fighting: 0.5,
      Poison: 0.25,
      Bug: 0.5,
      Rock: 0.5,
      Fairy: 0.5,
    },
  },
  32: {
    name: "Nidoran♂",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 46,
    attack: 57,
    defense: 40,
    specialAttack: 40,
    specialDefense: 40,
    speed: 50,
    totalBaseStats: 273,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  33: {
    name: "Nidorino",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 61,
    attack: 72,
    defense: 57,
    specialAttack: 55,
    specialDefense: 55,
    speed: 65,
    totalBaseStats: 365,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  34: {
    name: "Nidoking",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: "Ground",
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.GROUND,
    hp: 81,
    attack: 102,
    defense: 77,
    specialAttack: 85,
    specialDefense: 75,
    speed: 85,
    totalBaseStats: 505,
    weaknesses: {
      Water: 2,
      Ice: 2,
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Electric: 0,
      Fighting: 0.5,
      Poison: 0.25,
      Bug: 0.5,
      Rock: 0.5,
      Fairy: 0.5,
    },
  },
  35: {
    name: "Clefairy",
    spriteId: "",
    typeOne: "Fairy",
    typeTwo: null,
    typeOneId: PokemonType.FAIRY,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 70,
    attack: 45,
    defense: 48,
    specialAttack: 60,
    specialDefense: 65,
    speed: 35,
    totalBaseStats: 323,
    weaknesses: {
      Poison: 2,
      Steel: 2,
    },
    resistances: {
      Fighting: 0.5,
      Bug: 0.5,
      Dragon: 0,
      Dark: 0.5,
    },
  },
  36: {
    name: "Clefable",
    spriteId: "",
    typeOne: "Fairy",
    typeTwo: null,
    typeOneId: PokemonType.FAIRY,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 95,
    attack: 70,
    defense: 73,
    specialAttack: 95,
    specialDefense: 90,
    speed: 60,
    totalBaseStats: 483,
    weaknesses: {
      Poison: 2,
      Steel: 2,
    },
    resistances: {
      Fighting: 0.5,
      Bug: 0.5,
      Dragon: 0,
      Dark: 0.5,
    },
  },
  37: {
    name: "Vulpix",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 38,
    attack: 41,
    defense: 40,
    specialAttack: 50,
    specialDefense: 65,
    speed: 65,
    totalBaseStats: 299,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  38: {
    name: "Ninetales",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 73,
    attack: 76,
    defense: 75,
    specialAttack: 81,
    specialDefense: 100,
    speed: 100,
    totalBaseStats: 505,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  39: {
    name: "Jigglypuff",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: "Fairy",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FAIRY,
    hp: 115,
    attack: 45,
    defense: 20,
    specialAttack: 45,
    specialDefense: 25,
    speed: 20,
    totalBaseStats: 270,
    weaknesses: {
      Poison: 2,
      Steel: 2,
    },
    resistances: {
      Bug: 0.5,
      Ghost: 0,
      Dragon: 0,
      Dark: 0.5,
    },
  },
  40: {
    name: "Wigglytuff",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: "Fairy",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FAIRY,
    hp: 140,
    attack: 70,
    defense: 45,
    specialAttack: 85,
    specialDefense: 50,
    speed: 45,
    totalBaseStats: 435,
    weaknesses: {
      Poison: 2,
      Steel: 2,
    },
    resistances: {
      Bug: 0.5,
      Ghost: 0,
      Dragon: 0,
      Dark: 0.5,
    },
  },
  41: {
    name: "Zubat",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: "Flying",
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.FLYING,
    hp: 40,
    attack: 45,
    defense: 35,
    specialAttack: 30,
    specialDefense: 40,
    speed: 55,
    totalBaseStats: 245,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Psychic: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Poison: 0.5,
      Ground: 0,
      Bug: 0.25,
      Fairy: 0.5,
    },
  },
  42: {
    name: "Golbat",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: "Flying",
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.FLYING,
    hp: 75,
    attack: 80,
    defense: 70,
    specialAttack: 65,
    specialDefense: 75,
    speed: 90,
    totalBaseStats: 455,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Psychic: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Poison: 0.5,
      Ground: 0,
      Bug: 0.25,
      Fairy: 0.5,
    },
  },
  43: {
    name: "Oddish",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 45,
    attack: 50,
    defense: 55,
    specialAttack: 75,
    specialDefense: 65,
    speed: 30,
    totalBaseStats: 320,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5,
    },
  },
  44: {
    name: "Gloom",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 60,
    attack: 65,
    defense: 70,
    specialAttack: 85,
    specialDefense: 75,
    speed: 40,
    totalBaseStats: 395,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5,
    },
  },
  45: {
    name: "Vileplume",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 75,
    attack: 80,
    defense: 85,
    specialAttack: 110,
    specialDefense: 90,
    speed: 50,
    totalBaseStats: 490,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5,
    },
  },
  46: {
    name: "Paras",
    spriteId: "",
    typeOne: "Bug",
    typeTwo: "Grass",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.GRASS,
    hp: 35,
    attack: 70,
    defense: 55,
    specialAttack: 45,
    specialDefense: 55,
    speed: 25,
    totalBaseStats: 285,
    weaknesses: {
      Fire: 4,
      Ice: 2,
      Poison: 2,
      Flying: 4,
      Bug: 2,
      Rock: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Ground: 0.25,
    },
  },
  47: {
    name: "Parasect",
    spriteId: "",
    typeOne: "Bug",
    typeTwo: "Grass",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.GRASS,
    hp: 60,
    attack: 95,
    defense: 80,
    specialAttack: 60,
    specialDefense: 80,
    speed: 30,
    totalBaseStats: 405,
    weaknesses: {
      Fire: 4,
      Ice: 2,
      Poison: 2,
      Flying: 4,
      Bug: 2,
      Rock: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Ground: 0.25,
    },
  },
  48: {
    name: "Venonat",
    spriteId: "",
    typeOne: "Bug",
    typeTwo: "Poison",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.POISON,
    hp: 60,
    attack: 55,
    defense: 50,
    specialAttack: 40,
    specialDefense: 55,
    speed: 45,
    totalBaseStats: 305,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Psychic: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  49: {
    name: "Venomoth",
    spriteId: "",
    typeOne: "Bug",
    typeTwo: "Poison",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.POISON,
    hp: 70,
    attack: 65,
    defense: 60,
    specialAttack: 90,
    specialDefense: 75,
    speed: 90,
    totalBaseStats: 450,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Psychic: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  50: {
    name: "Diglett",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: null,
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 10,
    attack: 55,
    defense: 25,
    specialAttack: 35,
    specialDefense: 45,
    speed: 95,
    totalBaseStats: 265,
    weaknesses: {
      Water: 2,
      Grass: 2,
      Ice: 2,
    },
    resistances: {
      Electric: 0,
      Poison: 0.5,
      Rock: 0.5,
    },
  },
  51: {
    name: "Dugtrio",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: null,
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 35,
    attack: 100,
    defense: 50,
    specialAttack: 50,
    specialDefense: 70,
    speed: 120,
    totalBaseStats: 425,
    weaknesses: {
      Water: 2,
      Grass: 2,
      Ice: 2,
    },
    resistances: {
      Electric: 0,
      Poison: 0.5,
      Rock: 0.5,
    },
  },
  52: {
    name: "Meowth",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 40,
    attack: 45,
    defense: 35,
    specialAttack: 40,
    specialDefense: 40,
    speed: 90,
    totalBaseStats: 290,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    },
  },
  53: {
    name: "Persian",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 70,
    defense: 60,
    specialAttack: 65,
    specialDefense: 65,
    speed: 115,
    totalBaseStats: 440,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    },
  },
  54: {
    name: "Psyduck",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 50,
    attack: 52,
    defense: 48,
    specialAttack: 65,
    specialDefense: 50,
    speed: 55,
    totalBaseStats: 320,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  55: {
    name: "Golduck",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 80,
    attack: 82,
    defense: 78,
    specialAttack: 95,
    specialDefense: 80,
    speed: 85,
    totalBaseStats: 500,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  56: {
    name: "Mankey",
    spriteId: "",
    typeOne: "Fighting",
    typeTwo: null,
    typeOneId: PokemonType.FIGHTING,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 40,
    attack: 80,
    defense: 35,
    specialAttack: 35,
    specialDefense: 45,
    speed: 70,
    totalBaseStats: 305,
    weaknesses: {
      Flying: 2,
      Psychic: 2,
      Fairy: 2,
    },
    resistances: {
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5,
    },
  },
  57: {
    name: "Primeape",
    spriteId: "",
    typeOne: "Fighting",
    typeTwo: null,
    typeOneId: PokemonType.FIGHTING,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 105,
    defense: 60,
    specialAttack: 60,
    specialDefense: 70,
    speed: 95,
    totalBaseStats: 455,
    weaknesses: {
      Flying: 2,
      Psychic: 2,
      Fairy: 2,
    },
    resistances: {
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5,
    },
  },
  58: {
    name: "Growlithe",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 55,
    attack: 70,
    defense: 45,
    specialAttack: 70,
    specialDefense: 50,
    speed: 60,
    totalBaseStats: 350,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  59: {
    name: "Arcanine",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 90,
    attack: 110,
    defense: 80,
    specialAttack: 100,
    specialDefense: 80,
    speed: 95,
    totalBaseStats: 555,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  60: {
    name: "Poliwag",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 40,
    attack: 50,
    defense: 40,
    specialAttack: 40,
    specialDefense: 40,
    speed: 90,
    totalBaseStats: 300,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  61: {
    name: "Poliwhirl",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 65,
    defense: 65,
    specialAttack: 50,
    specialDefense: 50,
    speed: 90,
    totalBaseStats: 385,
    weaknesses: {
      Electric: 2,
      Grass: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5
    }
  },
  62: {
    name: "Poliwrath",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Fighting",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.FIGHTING,
    hp: 90,
    attack: 95,
    defense: 95,
    specialAttack: 70,
    specialDefense: 90,
    speed: 70,
    totalBaseStats: 510,
    weaknesses: {
      Electric: 2,
      Grass: 2,
      Flying: 2,
      Psychic: 2,
      Fairy: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5
    }
  },
  63: {
    name: "Abra",
    spriteId: "",
    typeOne: "Psychic",
    typeTwo: null,
    typeOneId: PokemonType.PSYCHIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 25,
    attack: 20,
    defense: 15,
    specialAttack: 105,
    specialDefense: 55,
    speed: 90,
    totalBaseStats: 310,
    weaknesses: {
      Bug: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Fighting: 0.5,
      Psychic: 0.5
    }
  },
  64: {
    name: "Kadabra",
    spriteId: "",
    typeOne: "Psychic",
    typeTwo: null,
    typeOneId: PokemonType.PSYCHIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 40,
    attack: 35,
    defense: 30,
    specialAttack: 120,
    specialDefense: 70,
    speed: 105,
    totalBaseStats: 400,
    weaknesses: {
      Bug: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Fighting: 0.5,
      Psychic: 0.5
    }
  },
  65: {
    name: "Alakazam",
    spriteId: "",
    typeOne: "Psychic",
    typeTwo: null,
    typeOneId: PokemonType.PSYCHIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 55,
    attack: 50,
    defense: 45,
    specialAttack: 135,
    specialDefense: 95,
    speed: 120,
    totalBaseStats: 500,
    weaknesses: {
      Bug: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Fighting: 0.5,
      Psychic: 0.5
    }
  },
  66: {
    name: "Machop",
    spriteId: "",
    typeOne: "Fighting",
    typeTwo: null,
    typeOneId: PokemonType.FIGHTING,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 70,
    attack: 80,
    defense: 50,
    specialAttack: 35,
    specialDefense: 35,
    speed: 35,
    totalBaseStats: 305,
    weaknesses: {
      Flying: 2,
      Psychic: 2,
      Fairy: 2
    },
    resistances: {
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5
    }
  },
  67: {
    name: "Machoke",
    spriteId: "",
    typeOne: "Fighting",
    typeTwo: null,
    typeOneId: PokemonType.FIGHTING,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 80,
    attack: 100,
    defense: 70,
    specialAttack: 50,
    specialDefense: 60,
    speed: 45,
    totalBaseStats: 405,
    weaknesses: {
      Flying: 2,
      Psychic: 2,
      Fairy: 2
    },
    resistances: {
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5
    }
  },
  68: {
    name: "Machamp",
    spriteId: "",
    typeOne: "Fighting",
    typeTwo: null,
    typeOneId: PokemonType.FIGHTING,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 90,
    attack: 130,
    defense: 80,
    specialAttack: 65,
    specialDefense: 85,
    speed: 55,
    totalBaseStats: 505,
    weaknesses: {
      Flying: 2,
      Psychic: 2,
      Fairy: 2
    },
    resistances: {
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5
    }
  },
  69: {
    name: "Bellsprout",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 50,
    attack: 75,
    defense: 35,
    specialAttack: 70,
    specialDefense: 30,
    speed: 40,
    totalBaseStats: 300,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5
    }
  },
  70: {
    name: "Weepinbell",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 65,
    attack: 90,
    defense: 50,
    specialAttack: 85,
    specialDefense: 45,
    speed: 55,
    totalBaseStats: 390,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5
    }
  },
  71: {
    name: "Victreebel",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Poison",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.POISON,
    hp: 80,
    attack: 105,
    defense: 65,
    specialAttack: 100,
    specialDefense: 70,
    speed: 70,
    TotalBaseStats: 490,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Flying: 2,
      Psychic: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.25,
      Fighting: 0.5,
      Fairy: 0.5,
    },
  },
  72: {
    name: "Tentacool",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Poison",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.POISON,
    hp: 40,
    attack: 40,
    defense: 35,
    specialAttack: 50,
    specialDefense: 100,
    speed: 70,
    TotalBaseStats: 335,
    weaknesses: {
      Electric: 2,
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Fighting: 0.5,
      Fairy: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Steel: 0.5,
    },
  },
  73: {
    name: "Tentacruel",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Poison",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.POISON,
    hp: 80,
    attack: 70,
    defense: 65,
    specialAttack: 80,
    specialDefense: 120,
    speed: 100,
    TotalBaseStats: 515,
    weaknesses: {
      Electric: 2,
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Fighting: 0.5,
      Fairy: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Steel: 0.5,
    },
  },
  74: {
    name: "Geodude",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Ground",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.GROUND,
    hp: 40,
    attack: 80,
    defense: 100,
    specialAttack: 30,
    specialDefense: 30,
    speed: 20,
    TotalBaseStats: 300,
    weaknesses: {
      Water: 4,
      Grass: 4,
      Ice: 2,
      Fighting: 2,
      Ground: 2,
      Steel: 2,
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.5,
      Electric: 0,
      Poison: 0.25,
      Flying: 0.5,
      Rock: 0.5,
    },
  },
  75: {
    name: "Graveler",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Ground",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.GROUND,
    hp: 55,
    attack: 95,
    defense: 115,
    specialAttack: 45,
    specialDefense: 45,
    speed: 35,
    TotalBaseStats: 390,
    weaknesses: {
      Water: 4,
      Grass: 4,
      Ice: 2,
      Fighting: 2,
      Ground: 2,
      Steel: 2,
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.5,
      Electric: 0,
      Poison: 0.25,
      Flying: 0.5,
      Rock: 0.5,
    },
  },
  76: {
    name: "Golem",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Ground",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.GROUND,
    hp: 80,
    attack: 120,
    defense: 130,
    specialAttack: 55,
    specialDefense: 65,
    speed: 45,
    TotalBaseStats: 495,
    weaknesses: {
      Water: 4,
      Grass: 4,
      Ice: 2,
      Fighting: 2,
      Ground: 2,
      Steel: 2,
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.5,
      Electric: 0,
      Poison: 0.25,
      Flying: 0.5,
      Rock: 0.5,
    },
  },
  77: {
    name: "Ponyta",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 50,
    attack: 85,
    defense: 55,
    specialAttack: 65,
    specialDefense: 65,
    speed: 90,
    TotalBaseStats: 410,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  78: {
    name: "Rapidash",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 100,
    defense: 70,
    specialAttack: 80,
    specialDefense: 80,
    speed: 105,
    TotalBaseStats: 500,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    },
  },
  79: {
    name: "Slowpoke",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Psychic",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.PSYCHIC,
    hp: 90,
    attack: 65,
    defense: 65,
    specialAttack: 40,
    specialDefense: 40,
    speed: 15,
    TotalBaseStats: 315,
    weaknesses: {
      Electric: 2,
      Grass: 2,
      Bug: 2,
      Ghost: 2,
      Dark: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Fighting: 0.5,
      Psychic: 0.5,
      Steel: 0.5,
    },
  },
  80: {
    name: "Slowbro",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Psychic",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.PSYCHIC,
    hp: 95,
    attack: 75,
    defense: 180,
    specialAttack: 130,
    specialDefense: 80,
    speed: 30,
    TotalBaseStats: 590,
    weaknesses: {
      Electric: 2,
      Grass: 2,
      Bug: 2,
      Ghost: 2,
      Dark: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Fighting: 0.5,
      Psychic: 0.5,
      Steel: 0.5,
    },
  },
  81: {
    name: "Magnemite",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: "Steel",
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.STEEL,
    hp: 25,
    attack: 35,
    defense: 70,
    specialAttack: 95,
    specialDefense: 55,
    speed: 45,
    totalBaseStats: 325,
    weaknesses: {
      Fire: 2,
      Fighting: 2,
      Ground: 4,
    },
    resistances: {
      Normal: 0.5,
      Electric: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Poison: 0,
      Flying: 0.25,
      Psychic: 0.5,
      Bug: 0.5,
      Rock: 0.5,
      Dragon: 0.5,
      Steel: 0.25,
      Fairy: 0.5,
    },
  },
  82: {
    name: "Magneton",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: "Steel",
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.STEEL,
    hp: 50,
    attack: 60,
    defense: 95,
    specialAttack: 120,
    specialDefense: 70,
    speed: 70,
    totalBaseStats: 465,
    weaknesses: {
      Fire: 2,
      Fighting: 2,
      Ground: 4,
    },
    resistances: {
      Normal: 0.5,
      Electric: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Poison: 0,
      Flying: 0.25,
      Psychic: 0.5,
      Bug: 0.5,
      Rock: 0.5,
      Dragon: 0.5,
      Steel: 0.25,
      Fairy: 0.5,
    },
  },
  83: {
    name: "Farfetch'd",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 52,
    attack: 90,
    defense: 55,
    specialAttack: 58,
    specialDefense: 62,
    speed: 60,
    totalBaseStats: 377,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Bug: 0.5,
      Ghost: 0,
    },
  },
  84: {
    name: "Doduo",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 35,
    attack: 85,
    defense: 45,
    specialAttack: 35,
    specialDefense: 35,
    speed: 75,
    totalBaseStats: 310,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Bug: 0.5,
      Ghost: 0,
    },
  },
  85: {
    name: "Dodrio",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: "Flying",
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.FLYING,
    hp: 60,
    attack: 110,
    defense: 70,
    specialAttack: 60,
    specialDefense: 60,
    speed: 110,
    totalBaseStats: 470,
    weaknesses: {
      Electric: 2,
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Bug: 0.5,
      Ghost: 0,
    },
  },
  86: {
    name: "Seel",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 45,
    defense: 55,
    specialAttack: 45,
    specialDefense: 70,
    speed: 45,
    totalBaseStats: 325,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  87: {
    name: "Dewgong",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Ice",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.ICE,
    hp: 90,
    attack: 70,
    defense: 80,
    specialAttack: 70,
    specialDefense: 95,
    speed: 70,
    totalBaseStats: 475,
    weaknesses: {
      Electric: 2,
      Grass: 2,
      Fighting: 2,
      Rock: 2,
    },
    resistances: {
      Water: 0.5,
      Ice: 0.25,
    },
  },
  88: {
    name: "Grimer",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 80,
    attack: 80,
    defense: 50,
    specialAttack: 40,
    specialDefense: 50,
    speed: 25,
    totalBaseStats: 325,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  89: {
    name: "Muk",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 105,
    attack: 105,
    defense: 75,
    specialAttack: 65,
    specialDefense: 100,
    speed: 50,
    totalBaseStats: 500,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  90: {
    name: "Shellder",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 30,
    attack: 65,
    defense: 100,
    specialAttack: 45,
    specialDefense: 25,
    speed: 40,
    totalBaseStats: 305,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    },
  },
  91: {
    name: "Cloyster",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Ice",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.ICE,
    hp: 50,
    attack: 95,
    defense: 180,
    specialAttack: 85,
    specialDefense: 45,
    speed: 70,
    totalBaseStats: 525,
    weaknesses: {
      Electric: 2,
      Grass: 2,
      Fighting: 2,
      Rock: 2
    },
    resistances: {
      Water: 0.5,
      Ice: 0.25
    }
  },
  92: {
    name: "Gastly",
    spriteId: "",
    typeOne: "Ghost",
    typeTwo: "Poison",
    typeOneId: PokemonType.GHOST,
    typeTwoId: PokemonType.POISON,
    hp: 30,
    attack: 35,
    defense: 30,
    specialAttack: 100,
    specialDefense: 35,
    speed: 80,
    totalBaseStats: 310,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Normal: 0,
      Grass: 0.5,
      Fighting: 0,
      Poison: 0.25,
      Bug: 0.25,
      Fairy: 0.5
    }
  },
  93: {
    name: "Haunter",
    spriteId: "",
    typeOne: "Ghost",
    typeTwo: "Poison",
    typeOneId: PokemonType.GHOST,
    typeTwoId: PokemonType.POISON,
    hp: 45,
    attack: 50,
    defense: 45,
    specialAttack: 115,
    specialDefense: 55,
    speed: 95,
    totalBaseStats: 405,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Normal: 0,
      Grass: 0.5,
      Fighting: 0,
      Poison: 0.25,
      Bug: 0.25,
      Fairy: 0.5
    }
  },
  94: {
    name: "Gengar",
    spriteId: "",
    typeOne: "Ghost",
    typeTwo: "Poison",
    typeOneId: PokemonType.GHOST,
    typeTwoId: PokemonType.POISON,
    hp: 60,
    attack: 65,
    defense: 80,
    specialAttack: 170,
    specialDefense: 95,
    speed: 130,
    totalBaseStats: 600,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Normal: 0,
      Grass: 0.5,
      Fighting: 0,
      Poison: 0.25,
      Bug: 0.25,
      Fairy: 0.5
    }
  },
  95: {
    name: "Onix",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Ground",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.GROUND,
    hp: 35,
    attack: 45,
    defense: 160,
    specialAttack: 30,
    specialDefense: 45,
    speed: 70,
    totalBaseStats: 385,
    weaknesses: {
      Water: 4,
      Grass: 4,
      Ice: 2,
      Fighting: 2,
      Ground: 2,
      Steel: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.5,
      Electric: 0,
      Poison: 0.25,
      Flying: 0.5,
      Rock: 0.5
    }
  },
  96: {
    name: "Drowzee",
    spriteId: "",
    typeOne: "Psychic",
    typeTwo: null,
    typeOneId: PokemonType.PSYCHIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 60,
    attack: 48,
    defense: 45,
    specialAttack: 43,
    specialDefense: 90,
    speed: 42,
    totalBaseStats: 328,
    weaknesses: {
      Bug: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Fighting: 0.5,
      Psychic: 0.5
    }
  },
  97: {
    name: "Hypno",
    spriteId: "",
    typeOne: "Psychic",
    typeTwo: null,
    typeOneId: PokemonType.PSYCHIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 85,
    attack: 73,
    defense: 70,
    specialAttack: 73,
    specialDefense: 115,
    speed: 67,
    totalBaseStats: 483,
    weaknesses: {
      Bug: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Fighting: 0.5,
      Psychic: 0.5
    }
  },
  98: {
    name: "Krabby",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 30,
    attack: 105,
    defense: 90,
    specialAttack: 25,
    specialDefense: 25,
    speed: 50,
    totalBaseStats: 325,
    weaknesses: {
      Electric: 2,
      Grass: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5
    }
  },
  99: {
    name: "Kingler",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 55,
    attack: 130,
    defense: 115,
    specialAttack: 50,
    specialDefense: 50,
    speed: 75,
    totalBaseStats: 475,
    weaknesses: {
      Electric: 2,
      Grass: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5
    }
  },
  100: {
    name: "Voltorb",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: null,
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 40,
    attack: 30,
    defense: 50,
    specialAttack: 55,
    specialDefense: 55,
    speed: 100,
    totalBaseStats: 330,
    weaknesses: {
      Ground: 2
    },
    resistances: {
      Electric: 0.5,
      Flying: 0.5,
      Steel: 0.5
    }
  },
  101: {
    name: "Electrode",
    spriteId: "",
    typeOnee: "Electric",
    typeTwo: null,
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 60,
    attack: 50,
    defense: 70,
    specialAttack: 80,
    specialDefense: 80,
    speed: 150,
    totalBaseStats: 490,
    weaknesses: {
      Ground: 2,
    },
    resistances: {
      Electric: 0.5,
      Flying: 0.5,
      Steel: 0.5,
    },
  },
  102: {
    name: "Exeggcute",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Psychic",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.PSYCHIC,
    hp: 60,
    attack: 40,
    defense: 80,
    specialAttack: 60,
    specialDefense: 45,
    speed: 40,
    totalBaseStats: 325,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Poison: 2,
      Flying: 2,
      Bug: 4,
      Ghost: 2,
      Dark: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.5,
      Fighting: 0.5,
      Ground: 0.5,
    },
  },
  103: {
    name: "Exeggutor",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: "Psychic",
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.PSYCHIC,
    hp: 95,
    attack: 95,
    defense: 85,
    specialAttack: 125,
    specialDefense: 75,
    speed: 55,
    totalBaseStats: 530,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Poison: 2,
      Flying: 2,
      Bug: 4,
      Ghost: 2,
      Dark: 2,
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.5,
      Fighting: 0.5,
      Ground: 0.5,
    },
  },
  104: {
    name: "Cubone",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: null,
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 50,
    attack: 50,
    defense: 95,
    specialAttack: 40,
    specialDefense: 50,
    speed: 35,
    totalBaseStats: 320,
    weaknesses: {
      Water: 2,
      Grass: 2,
      Ice: 2,
    },
    resistances: {
      Electric: 0,
      Poison: 0.5,
      Rock: 0.5,
    },
  },
  105: {
    name: "Marowak",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: null,
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 60,
    attack: 80,
    defense: 110,
    specialAttack: 50,
    specialDefense: 80,
    speed: 45,
    totalBaseStats: 425,
    weaknesses: {
      Water: 2,
      Grass: 2,
      Ice: 2,
    },
    resistances: {
      Electric: 0,
      Poison: 0.5,
      Rock: 0.5,
    },
  },
  106: {
    name: "Hitmonlee",
    spriteId: "",
    typeOne: "Fighting",
    typeTwo: null,
    typeOneId: PokemonType.FIGHTING,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 50,
    attack: 120,
    defense: 53,
    specialAttack: 35,
    specialDefense: 110,
    speed: 87,
    totalBaseStats: 455,
    weaknesses: {
      Flying: 2,
      Psychic: 2,
      Fairy: 2,
    },
    resistances: {
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5,
    },
  },
  107: {
    name: "Hitmonchan",
    spriteId: "",
    typeOne: "Fighting",
    typeTwo: null,
    typeOneId: PokemonType.FIGHTING,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 50,
    attack: 105,
    defense: 79,
    specialAttack: 35,
    specialDefense: 110,
    speed: 76,
    totalBaseStats: 455,
    weaknesses: {
      Flying: 2,
      Psychic: 2,
      Fairy: 2,
    },
    resistances: {
      Bug: 0.5,
      Rock: 0.5,
      Dark: 0.5,
    },
  },
  108: {
    name: "Lickitung",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 90,
    attack: 55,
    defense: 75,
    specialAttack: 60,
    specialDefense: 75,
    speed: 30,
    totalBaseStats: 385,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    },
  },
  109: {
    name: "Koffing",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 40,
    attack: 65,
    defense: 95,
    specialAttack: 60,
    specialDefense: 45,
    speed: 35,
    totalBaseStats: 340,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  110: {
    name: "Weezing",
    spriteId: "",
    typeOne: "Poison",
    typeTwo: null,
    typeOneId: PokemonType.POISON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 90,
    defense: 120,
    specialAttack: 85,
    specialDefense: 70,
    speed: 60,
    totalBaseStats: 490,
    weaknesses: {
      Ground: 2,
      Psychic: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Poison: 0.5,
      Bug: 0.5,
      Fairy: 0.5,
    },
  },
  111: {
    name: "Rhyhorn",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: "Rock",
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.ROCK,
    hp: 80,
    attack: 85,
    defense: 95,
    specialAttack: 30,
    specialDefense: 30,
    speed: 25,
    totalBaseStats: 345,
    weaknesses: {
      Water: 4,
      Grass: 4,
      Ice: 2,
      Fighting: 2,
      Ground: 2,
      Steel: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.5,
      Electric: 0,
      Poison: 0.25,
      Flying: 0.5,
      Rock: 0.5
    }
  },
  112: {
    name: "Rhydon",
    spriteId: "",
    typeOne: "Ground",
    typeTwo: "Rock",
    typeOneId: PokemonType.GROUND,
    typeTwoId: PokemonType.ROCK,
    hp: 105,
    attack: 130,
    defense: 120,
    specialAttack: 45,
    specialDefense: 45,
    speed: 40,
    totalBaseStats: 485,
    weaknesses: {
      Water: 4,
      Grass: 4,
      Ice: 2,
      Fighting: 2,
      Ground: 2,
      Steel: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.5,
      Electric: 0,
      Poison: 0.25,
      Flying: 0.5,
      Rock: 0.5
    }
  },
  113: {
    name: "Chansey",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 250,
    attack: 5,
    defense: 5,
    specialAttack: 35,
    specialDefense: 105,
    speed: 50,
    totalBaseStats: 450,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  113: {
    name: "Chansey",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 250,
    attack: 5,
    defense: 5,
    specialAttack: 35,
    specialDefense: 105,
    speed: 50,
    totalBaseStats: 450,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  114: {
    name: "Tangela",
    spriteId: "",
    typeOne: "Grass",
    typeTwo: null,
    typeOneId: PokemonType.GRASS,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 55,
    defense: 115,
    specialAttack: 100,
    specialDefense: 40,
    speed: 60,
    totalBaseStats: 435,
    weaknesses: {
      Fire: 2,
      Ice: 2,
      Poison: 2,
      Flying: 2,
      Bug: 2
    },
    resistances: {
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.5,
      Ground: 0.5
    }
  },
  115: {
    name: "Kangaskhan",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 105,
    attack: 125,
    defense: 100,
    specialAttack: 60,
    specialDefense: 100,
    speed: 100,
    totalBaseStats: 590,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  116: {
    name: "Horsea",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 30,
    attack: 40,
    defense: 70,
    specialAttack: 70,
    specialDefense: 25,
    speed: 60,
    totalBaseStats: 295,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    }
  },
  117: {
    name: "Seadra",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 55,
    attack: 65,
    defense: 95,
    specialAttack: 95,
    specialDefense: 45,
    speed: 85,
    totalBaseStats: 440,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    }
  },
  118: {
    name: "Goldeen",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 45,
    attack: 67,
    defense: 60,
    specialAttack: 35,
    specialDefense: 50,
    speed: 63,
    totalBaseStats: 320,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    }
  },
  119: {
    name: "Seaking",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 80,
    attack: 92,
    defense: 65,
    specialAttack: 65,
    specialDefense: 80,
    speed: 68,
    totalBaseStats: 450,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    }
  },
  120: {
    name: "Staryu",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 30,
    attack: 45,
    defense: 55,
    specialAttack: 70,
    specialDefense: 55,
    speed: 85,
    totalBaseStats: 340,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    }
  },
  121: {
    name: "Starmie",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Psychic",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.PSYCHIC,
    hp: 60,
    attack: 75,
    defense: 85,
    specialAttack: 100,
    specialDefense: 85,
    speed: 115,
    totalBaseStats: 520,
    weaknesses: {
      Electric: 2,
      Grass: 2,
      Bug: 2,
      Ghost: 2,
      Dark: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Fighting: 0.5,
      Psychic: 0.5,
      Steel: 0.5,
    }
  },
  122: {
    name: "Mr. Mime",
    spriteId: "",
    typeOne: "Psychic",
    typeTwo: "Fairy",
    typeOneId: PokemonType.PSYCHIC,
    typeTwoId: PokemonType.FAIRY,
    hp: 40,
    attack: 45,
    defense: 65,
    specialAttack: 100,
    specialDefense: 120,
    speed: 90,
    totalBaseStats: 460,
    weaknesses: {
      Poison: 2,
      Ghost: 2,
      Steel: 2
    },
    resistances: {
      Fighting: 0.25,
      Psychic: 0.5,
      Dragon: 0,
    }
  },
  123: {
    name: "Scyther",
    spriteId: "",
    typeOne: "Bug",
    typeTwo: "Flying",
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.FLYING,
    hp: 70,
    attack: 110,
    defense: 80,
    specialAttack: 55,
    specialDefense: 80,
    speed: 105,
    totalBaseStats: 500,
    weaknesses: {
      Fire: 2,
      Electric: 2,
      Ice: 2,
      Flying: 2,
      Rock: 4
    },
    resistances: {
      Grass: 0.25,
      Fighting: 0.25,
      Ground: 0,
      Bug: 0.5
    }
  },
  124: {
    name: "Jynx",
    spriteId: "",
    typeOne: "Ice",
    typeTwo: "Psychic",
    typeOneId: PokemonType.ICE,
    typeTwoId: PokemonType.PSYCHIC,
    hp: 65,
    attack: 50,
    defense: 35,
    specialAttack: 115,
    specialDefense: 95,
    speed: 95,
    totalBaseStats: 455,
    weaknesses: {
      Fire: 2,
      Bug: 2,
      Rock: 2,
      Ghost: 2,
      Dark: 2,
      Steel: 2
    },
    resistances: {
      Ice: 0.5,
      Psychic: 0.5,
    }
  },
  125: {
    name: "Electabuzz",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: null,
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 83,
    defense: 57,
    specialAttack: 95,
    specialDefense: 85,
    speed: 105,
    totalBaseStats: 490,
    weaknesses: {
      Ground: 2,

    },
    resistances: {
      Electric: 0.5,
      Flying: 0.5,
      Steel: 0.5,

    }
  },
  126: {
    name: "Magmar",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 95,
    defense: 57,
    specialAttack: 100,
    specialDefense: 85,
    speed: 93,
    totalBaseStats: 495,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    }
  },
  127: {
    name: "Pinsir",
    spriteId: "",
    typeOne: "Bug",
    typeTwo: null,
    typeOneId: PokemonType.BUG,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 125,
    defense: 100,
    specialAttack: 55,
    specialDefense: 70,
    speed: 85,
    totalBaseStats: 500,
    weaknesses: {
      Fire: 2,
      Flying: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Fighting: 0.5,
      Ground: 0.5,
    }
  },
  128: {
    name: "Tauros",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 75,
    attack: 100,
    defense: 95,
    specialAttack: 40,
    specialDefense: 70,
    speed: 110,
    totalBaseStats: 490,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  129: {
    name: "Magikarp",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 20,
    attack: 10,
    defense: 55,
    specialAttack: 15,
    specialDefense: 20,
    speed: 80,
    totalBaseStats: 200,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    }
  },
  130: {
    name: "Gyarados",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Flying",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.FLYING,
    hp: 95,
    attack: 125,
    defense: 79,
    specialAttack: 60,
    specialDefense: 100,
    speed: 81,
    totalBaseStats: 540,
    weaknesses: {
      Electric: 4,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Fighting: 0.5,
      Ground: 0,
      Bug: 0.5,
      Steel: 0.5
    }
  },
  131: {
    name: "Lapras",
    spriteId: "",
    typeOne: "Water",
    typeTwo: "Ice",
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.ICE,
    hp: 130,
    attack: 85,
    defense: 80,
    specialAttack: 85,
    specialDefense: 95,
    speed: 60,
    totalBaseStats: 535,
    weaknesses: {
      Electric: 2,
      Grass: 2,
      Fighting: 2,
      Rock: 2
    },
    resistances: {
      Water: 0.5,
      Ice: 0.25,
    }
  },
  132: {
    name: "Ditto",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 48,
    attack: 48,
    defense: 48,
    specialAttack: 48,
    specialDefense: 48,
    speed: 48,
    totalBaseStats: 288,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  133: {
    name: "Eevee",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 55,
    attack: 55,
    defense: 50,
    specialAttack: 45,
    specialDefense: 65,
    speed: 55,
    totalBaseStats: 325,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  134: {
    name: "Vaporeon",
    spriteId: "",
    typeOne: "Water",
    typeTwo: null,
    typeOneId: PokemonType.WATER,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 130,
    attack: 65,
    defense: 60,
    specialAttack: 110,
    specialDefense: 95,
    speed: 65,
    totalBaseStats: 525,
    weaknesses: {
      Electric: 2,
      Grass: 2,
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Ice: 0.5,
      Steel: 0.5,
    }
  },
  135: {
    name: "Jolteon",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: null,
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 65,
    defense: 60,
    specialAttack: 110,
    specialDefense: 95,
    speed: 130,
    totalBaseStats: 525,
    weaknesses: {
      Ground: 2,

    },
    resistances: {
      Electric: 0.5,
      Flying: 0.5,
      Steel: 0.5,

    }
  },
  136: {
    name: "Flareon",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: null,
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 130,
    defense: 60,
    specialAttack: 95,
    specialDefense: 110,
    speed: 65,
    totalBaseStats: 525,
    weaknesses: {
      Water: 2,
      Ground: 2,
      Rock: 2,
    },
    resistances: {
      Fire: 0.5,
      Grass: 0.5,
      Ice: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Fairy: 0.5,
    }
  },
  137: {
    name: "Porygon",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 65,
    attack: 60,
    defense: 70,
    specialAttack: 85,
    specialDefense: 75,
    speed: 40,
    totalBaseStats: 395,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  138: {
    name: "Omanyte",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Water",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.WATER,
    hp: 35,
    attack: 40,
    defense: 100,
    specialAttack: 90,
    specialDefense: 55,
    speed: 35,
    totalBaseStats: 355,
    weaknesses: {
      Electric: 2,
      Grass: 4,
      Fighting: 2,
      Ground: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.25,
      Ice: 0.5,
      Poison: 0.5,
      Flying: 0.5,
    }
  },
  139: {
    name: "Omastar",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Water",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.WATER,
    hp: 70,
    attack: 60,
    defense: 125,
    specialAttack: 115,
    specialDefense: 70,
    speed: 55,
    totalBaseStats: 495,
    weaknesses: {
      Electric: 2,
      Grass: 4,
      Fighting: 2,
      Ground: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.25,
      Ice: 0.5,
      Poison: 0.5,
      Flying: 0.5,
    }
  },
  140: {
    name: "Kabuto",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Water",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.WATER,
    hp: 30,
    attack: 80,
    defense: 90,
    specialAttack: 55,
    specialDefense: 45,
    speed: 55,
    totalBaseStats: 355,
    weaknesses: {
      Electric: 2,
      Grass: 4,
      Fighting: 2,
      Ground: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.25,
      Ice: 0.5,
      Poison: 0.5,
      Flying: 0.5,
    }
  },
  141: {
    name: "Kabutops",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Water",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.WATER,
    hp: 60,
    attack: 115,
    defense: 105,
    specialAttack: 65,
    specialDefense: 70,
    speed: 80,
    totalBaseStats: 495,
    weaknesses: {
      Electric: 2,
      Grass: 4,
      Fighting: 2,
      Ground: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.25,
      Ice: 0.5,
      Poison: 0.5,
      Flying: 0.5,
    }
  },
  142: {
    name: "Aerodactyl",
    spriteId: "",
    typeOne: "Rock",
    typeTwo: "Flying",
    typeOneId: PokemonType.ROCK,
    typeTwoId: PokemonType.FLYING,
    hp: 80,
    attack: 105,
    defense: 65,
    specialAttack: 60,
    specialDefense: 75,
    speed: 130,
    totalBaseStats: 515,
    weaknesses: {
      Electric: 2,
      Water: 4,
      Ice: 2,
      Rock: 2,
      Steel: 2
    },
    resistances: {
      Normal: 0.5,
      Fire: 0.5,
      Poison: 0.5,
      Ground: 0,
      Bug: 0.5,
      Flying: 0.5
    }
  },
  143: {
    name: "Snorlax",
    spriteId: "",
    typeOne: "Normal",
    typeTwo: null,
    typeOneId: PokemonType.NORMAL,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 160,
    attack: 110,
    defense: 65,
    specialAttack: 65,
    specialDefense: 110,
    speed: 30,
    totalBaseStats: 540,
    weaknesses: {
      Fighting: 2,
    },
    resistances: {
      Ghost: 0,
    }
  },
  144: {
    name: "Articuno",
    spriteId: "",
    typeOne: "Ice",
    typeTwo: "Flying",
    typeOneId: PokemonType.ICE,
    typeTwoId: PokemonType.FLYING,
    hp: 90,
    attack: 85,
    defense: 100,
    specialAttack: 95,
    specialDefense: 125,
    speed: 85,
    totalBaseStats: 580,
    weaknesses: {
      Fire: 2,
      Electric: 2,
      Rock: 4,
      Steel: 2
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Bug: 0.5
    }
  },
  145: {
    name: "Zapdos",
    spriteId: "",
    typeOne: "Electric",
    typeTwo: "Flying",
    typeOneId: PokemonType.ELECTRIC,
    typeTwoId: PokemonType.FLYING,
    hp: 90,
    attack: 90,
    defense: 85,
    specialAttack: 125,
    specialDefense: 90,
    speed: 100,
    totalBaseStats: 580,
    weaknesses: {
      Ice: 2,
      Rock: 2,
    },
    resistances: {
      Grass: 0.5,
      Ground: 0,
      Fighting: 0.5,
      Bug: 0.5,
      Steel: 0.5,
      Flying: 0.5
    }
  },
  146: {
    name: "Moltres",
    spriteId: "",
    typeOne: "Fire",
    typeTwo: "Flying",
    typeOneId: PokemonType.FIRE,
    typeTwoId: PokemonType.FLYING,
    hp: 90,
    attack: 100,
    defense: 90,
    specialAttack: 125,
    specialDefense: 85,
    speed: 90,
    totalBaseStats: 580,
    weaknesses: {
      Water: 2,
      Electric: 2,
      Rock: 4,
    },
    resistances: {
      Grass: 0.25,
      Ground: 0,
      Fire: 0.5,
      Fighting: 0.5,
      Bug: 0.25,
      Steel: 0.5,
      Fairy: 0.5
    }
  },
  147: {
    name: "Dratini",
    spriteId: "",
    typeOne: "Dragon",
    typeTwo: null,
    typeOneId: PokemonType.DRAGON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 41,
    attack: 64,
    defense: 45,
    specialAttack: 50,
    specialDefense: 50,
    speed: 50,
    totalBaseStats: 300,
    weaknesses: {
      Ice: 2,
      Dragon: 2,
      Fairy: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.5
    }
  },
  148: {
    name: "Dragonair",
    spriteId: "",
    typeOne: "Dragon",
    typeTwo: null,
    typeOneId: PokemonType.DRAGON,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 61,
    attack: 84,
    defense: 65,
    specialAttack: 70,
    specialDefense: 70,
    speed: 70,
    totalBaseStats: 420,
    weaknesses: {
      Ice: 2,
      Dragon: 2,
      Fairy: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Electric: 0.5,
      Grass: 0.5
    }
  },
  149: {
    name: "Dragonite",
    spriteId: "",
    typeOne: "Dragon",
    typeTwo: null,
    typeOneId: PokemonType.DRAGON,
    typeTwoId: PokemonType.FLYING,
    hp: 91,
    attack: 134,
    defense: 95,
    specialAttack: 100,
    specialDefense: 100,
    speed: 80,
    totalBaseStats: 600,
    weaknesses: {
      Ice: 4,
      Rock: 2,
      Dragon: 2,
      Fairy: 2
    },
    resistances: {
      Fire: 0.5,
      Water: 0.5,
      Fighting: 0.5,
      Grass: 0.25,
      Ground: 0,
      Bug: 0.5
    }
  },
  150: {
    name: "Mewtwo",
    spriteId: "",
    typeOne: "Psychic",
    typeTwo: null,
    typeOneId: PokemonType.PSYCHIC,
    typeTwoId: PokemonType.MONOTYPE,
    hp: 106,
    attack: 110,
    defense: 90,
    specialAttack: 154,
    specialDefense: 90,
    speed: 130,
    totalBaseStats: 680,
    weaknesses: {
      Bug: 2,
      Ghost: 2,
      Dark: 2,
    },
    resistances: {
      Fighting: 0.5,
      Psychic: 0.5,
    }
  },

};

